services:
  grafana:
    image: 'grafana/grafana-oss@sha256:2d1f9ae67c1778d33e291d4c3c759cd8b650e67491f02533499eb950e075eeb5'
    ports:
      - "3000:3000"
    links:
      - prometheus
    dns:
      - 8.8.8.8
  prometheus:
    image: 'prom/prometheus@sha256:e4254400b85610324913f0dc4acf92603d9984e7519414c5a12811aa6146acc3'
    volumes:
      - ./prometheus/:/etc/prometheus/
    command: 
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    links:
      - traffic
  traffic:
    image: 'ghcr.io/grafana/github-traffic@sha256:94a9546415e019484a5d3197138148d3ffcb17842c8e852584f03a9848e6f407'
    ports: 
      - "8001:8001"
    env_file:
      - .env
    restart:
      on-failure
    dns:
      - 8.8.8.8
